version: '3.1'
services:
  mongo:
    image: mongo
    restart: $MONGO_RESTART
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: cb
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - '~/.data/sensors:/data/db'

  mongo-express:
    image: mongo-express
    restart: $MONGO_EXPRESS_RESTART
    depends_on:
      - mongo
    ports:
      - 8888:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  cbn:
    image: cbn:latest
    restart: $CBN_RESTART
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGO_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      REGULAR_USER: $REGULAR_USER
      REGULAR_USER_PASSWORD: $REGULAR_USER_PASSWORD
      ADMIN_USER: $ADMIN_USER
      ADMIN_USER_PASSWORD: $ADMIN_USER_PASSWORD
      MONGO_HOST: $MONGO_HOST
      SENSOR_USER: $SENSOR_USER
      SENSOR_USER_PASSWORD: $SENSOR_USER_PASSWORD

